version: "3.8"

services:
  app:
    image: rfqma/katabersama-be:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    # add this line in docker-compose.yml on vps
    # env_file:
    #   - .env
    ports:
      - "4001:4001"
    restart: always
