import "dotenv/config";

const CONFIG = {
  DEV_URL: process.env.DEV_URL,
  PROD_URL: process.env.PROD_URL,
  MONGODB_URL: process.env.MONGODB_URL,
  JWT_PUBLIC_KEY: process.env.JWT_PUBLIC_KEY,
  JWT_PRIVATE_KEY: process.env.JWT_PRIVATE_KEY,
  CONTABO_STORAGE_BUCKET_URL: process.env.CONTABO_STORAGE_BUCKET_URL,
  CONTABO_STORAGE_BUCKET_URL_PUBLIC:
    process.env.CONTABO_STORAGE_BUCKET_URL_PUBLIC,
  CONTABO_STORAGE_BUCKET_ACCESS_KEY:
    process.env.CONTABO_STORAGE_BUCKET_ACCESS_KEY,
  CONTABO_STORAGE_BUCKET_SECRET_KEY:
    process.env.CONTABO_STORAGE_BUCKET_SECRET_KEY,
};

export default CONFIG;
